[package]
name = "lokb-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "lokb"
path = "src/main.rs"

[dependencies]
lokb-core = { workspace = true }
lokb-storage = { workspace = true }
lokb-ingest = { path = "../lokb-ingest" }
lokb-search = { path = "../lokb-search" }
lokb-pipeline = { workspace = true }
lokb-parsers = { path = "../lokb-parsers" }
lokb-embed = { path = "../lokb-embed" }
lokb-llm = { path = "../lokb-llm" }
lokb-serve = { path = "../lokb-serve" }
tokio = { workspace = true }
clap = { version = "4", features = ["derive"] }
chrono = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
zstd = { workspace = true }
notify = { workspace = true }
notify-debouncer-mini = { workspace = true }
lokb-render = { path = "../lokb-render" }
crossbeam-channel = { workspace = true }
num_cpus = { workspace = true }
ctrlc = { workspace = true }

[dev-dependencies]
cucumber = "0.22"
futures = "0.3"
serde_json = { workspace = true }
shell-words = "1"
tempfile = "3"

[[test]]
name = "e2e"
harness = false
path = "tests/e2e.rs"
